### ISSUE TITLE
Sätt "StrictHostKeyChecking yes" i /etc/ssh/ssh_config på produktionsmaskiner

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#117]
För utveckling använder vi "StrictHostKeyChecking yes". Detta gör det möjligt att installera efter DNS-förändringar utan komplikationer.

Detta är olämpligt i en produktionsmiljö. Om vi använder nuvarande Jenkins-script ska targets "prod" och "beta" ändras!

**Comment by karejonssondov** [comment]
Fixat!

**Comment by cheijken** [comment]
Detta är ingen inställning som gör på produktionsservrar, utan på byggservrar. Som jenkins.
Det är jenkins som uppdaterar en DNS target och "mår dålig" när vi ominstallerar en VM och den tror att det pågår en "man in the middle attack". Den genererar då en fråga eller alternativt spärrar vidare access. Detta resulterar i att jenkins, headless script, fallerar pg att de inte tillåts/stödjer en tangentbordsinput.

**Comment by kamidev** [comment]
Nästa release kommer att ske mot beta.lagrummet.se i vår utvecklingsmiljö. Vi öppnar det här ärendet om det blir mer relevant för kommande releaser.
