### ISSUE TITLE
Flytta ut properties/inställningar ur war filen till en gemensam config katalog

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#141]

**Comment by cheijken** [comment]
Ok, blir en "groovy" config fil som läses in av "ConfigSlurper".
Filer (katalog: /etc/rdl/ ):
main-config.groovy
service-config.groovy
checker-config.groovy
osv...

**Comment by kamidev** [comment]
Slänger vi på en adapter, som @jeldeklint föreslår?

**Comment by cheijken** [comment]
I ett första steg i rätt riktning heter dem rinfo-main.properties osv...

**Comment by cheijken** [comment]
En första version men samma properties filer som tidigare, utlokaliserade, utan "ConfigSlurper".
Vet ej om vi i detta skedet skall göra mer "avancerad" lösning.
Om det är läge att stänga denna issue, så går det att installera exempelvis test.
Kontrollera att prop filer installera på /etc/rinfo/ och ändra lite "lägtligt" förstörande i dessa och starta om tomcat. För att se i loggen och ev i webläsaren att ändringarna i prop filerna har slagit igenom.

**Comment by kamidev** [comment]
Installerad på test och demo. Alla tester passerar.
