### ISSUE TITLE
Hantera multipla förekomster av vissa predikat

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#146]
Se rinfo/lagrummet.se#157
Flyttar merparten av ärendet hit, då implementationen görs helt i service.
P.g.a hur exempelvis RK (eller snare riksdag och regering..) har modellerat vissa SFS:er förekommer det multipla titlar, för samma SFS-identifierare vilket inte är helt bra när vi visar exempelvis en konsolidering - då det är svårt att avgöra vilken titel på en ändring som hör till vilken konsolidering.

**Comment by jeldeklint** [comment]
Just nu är det hårdkodat till `dct:title` men det skulle vara enkelt att använda en lista istället.

**Comment by jeldeklint** [comment]
den här är done-ish. finns utrymme för förbättring.

**Comment by kamidev** [comment]
Testat koden. Ser ut att uppfylla det som efterfrågas i https://github.com/rinfo/lagrummet.se/issues/157.

**Comment by kamidev** [comment]
Testat koden. Försöker uppfylla testen som beskrivs i rinfo/lagrummet.se#157. Men får fortfarande en lista med flera titlar för Förordning (2007:636).

**Comment by jeldeklint** [comment]
Har fixat till den här nu, den skulle ha testats löst innan den mergades. Den hade inte gjort sig förtjänt av `done` flaggan, ingen aning vad jag tänkte :-1:

**Comment by kamidev** [comment]
Testat och checkat in på develop Ger förväntat resultat för rinfo/lagrummet.se#157.
