### ISSUE TITLE
Fab-scriptet server.ping_verify skapar loggrapporter som Jenkins inte kan läsa

### ISSUE THREAD

**Issue by cheijken** [rinfo/rdl#150]
Vet inte exakt vad den skall placeras, men ping_verify jekninsjobb kan inte läsa felloggen, när det kommer in ett fel i den.

**Comment by cheijken** [comment]
Felet går att återskapa med http://www.xmlvalidation.com/ genom att köra ovan xml där.

**Comment by cheijken** [comment]
Har fixat xml:en i feature ''feature/150_ping_verify_report_fail''.
Testa genom att ändra DNS i hosts filen för service.demo.lagrummet.se till ex 127.0.0.1 och kör scriptet ping_verify.sh.

**Comment by cheijken** [comment]
Även uppdaterad dokumentationen för installationen av jenkins och utveckling i wikin.

**Comment by kamidev** [comment]
Verifierat enligt kommentar ovan. Stänger ärendet.
