### ISSUE TITLE
Tvätta indata till elasticseach

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#151]
Idag går det att göra sökningar, från lagrummet på t.ex. `\"sökord` vilket slutar som omatchade citat-tecken-"par" i sökfrågan och en arg sökmotor med fel i loggarna. Då "dynamic scripting" är avslaget _borde_ det inte vara något direkt säkerhets problem, såvitt jag vet..

**Comment by jeldeklint** [comment]
se t.e.x http://stackoverflow.com/questions/16205341/symbols-in-query-string-for-elasticsearch för inspiration

**Comment by karejonssondov** [comment]
Fann denna
http://stackoverflow.com/questions/22031329/how-to-escape-all-special-characters-from-whole-string-at-one-go-in-java

Skrev koden 
	public static final String regex = "([+\\-!\\(\\){}\\[\\]\\/^\"~*?:\\\\]|[&\\|]{2})";
	public static final String replacement = "\\\\\$1";

samt ändrade i anropet i toQueryItem enligt
    def toQueryItem(final String nameArg) {
		String name = nameArg.replaceAll(regex, replacement);

**Comment by karejonssondov** [comment]
Vid sökning på {"query": {"match": {"_all": "a"}}} får jag en sida med budskapet 

"Den använda söksträngen är inte giltig, kontrollera den och sök igen"

Hur gör man ett fullständigt testfall?

**Comment by jeldeklint** [comment]
jag tvivlar på att det är meningen att det ska gå att skicka in den frågan från lagrummet. Det testet ser ut att göra är ju att testa escaping av specialtecken, det säger inget om att frågan är okej eller inte.

**Comment by lalindqv** [comment]
Sökning på tex "2008:" ger ett felmeddelande:

![151a](https://cloud.githubusercontent.com/assets/9251555/6551358/8127df5c-c637-11e4-86a8-d75f408d7259.png)

**Comment by lalindqv** [comment]
Eva:
Söker på "sfs1998:150" (utan blank mellan sfs och 1998:150)
Resultat:
![felskrivningsintolerans](https://cloud.githubusercontent.com/assets/9251555/6551389/08ef909c-c638-11e4-8e92-e8984321be5a.PNG)

Kommentar från Jonas: Ingen åtgärd till 2.3 Förväntas fungera något bättre när detta ärende är stängt.

**Comment by lalindqv** [comment]
Exakt träff rankas för lågt ( i detta fall bör 1979:13 presenteras först) :
![151b](https://cloud.githubusercontent.com/assets/9251555/6551407/4c4790d8-c638-11e4-8a26-c7813375d50a.png)

**Comment by lalindqv** [comment]
Eva: Får gul varning fram tills strängen blir komplett och avslutats med ”
![151c](https://cloud.githubusercontent.com/assets/9251555/6552479/8f3597ce-c646-11e4-99d5-41349e080741.PNG)

**Comment by kamidev** [comment]
Testa att skriva in kolon och andra specialtecken. Går det att framkalla en krasch?

**Comment by lalindqv** [comment]
"\\\\AAA" ger 4 träff på "AAA"
_hundskatt ger inga träffar, medan hundskatt ger ett tusental.
":" ger inga träffar 

Fel om jag söker på !"#¤%&/()=:
![fel](https://cloud.githubusercontent.com/assets/9251555/6620682/5f25ef3c-c8d2-11e4-9fbb-a1b45760ab59.PNG)


Sökning med semikolon på "1999;175" ger 0 träffar: 
(sökningen i lagrummet.se tycker jag ger en relevant träff)

![semikolon](https://cloud.githubusercontent.com/assets/9251555/6620377/b37caca8-c8d0-11e4-9eb8-243cd2c76f6e.PNG)

hade förväntat mig ungefär samma resultat som för sök med kolon:
![kolon](https://cloud.githubusercontent.com/assets/9251555/6620442/05c5f960-c8d1-11e4-80c8-7699d5ddb42c.PNG)

**Comment by lalindqv** [comment]
Sökning på "2006:" (med kolon) ger inte träff på Beteckning i första hand, vilket jag hade förväntat mig:
![2006](https://cloud.githubusercontent.com/assets/9251555/6634516/f0630fb6-c959-11e4-8df2-7ac198c6ec52.PNG)

Sökning på "2006" (utan kolon) ger dock träff på beteckning i första hand ( verkar  alltså OK):
![2006 utan](https://cloud.githubusercontent.com/assets/9251555/6634528/4c123904-c95a-11e4-8e7f-b73cedee3f5c.PNG)

**Comment by lalindqv** [comment]
Samma som för "2006:" och "2006" ovan gäller också sökning på "1998:" och "1998"

![1998](https://cloud.githubusercontent.com/assets/9251555/6634554/990219e6-c95a-11e4-8933-cef6a875cd04.PNG)

![1988utan](https://cloud.githubusercontent.com/assets/9251555/6634569/c716eece-c95a-11e4-9179-d31a40cadcbb.PNG)

**Comment by lalindqv** [comment]
Sökning på "1986" resp "1986:" ger också fler träffar om jag inte anväden kolon:

![1986](https://cloud.githubusercontent.com/assets/9251555/6634633/7ce3fd8c-c95b-11e4-9fbf-c53d96cf325a.PNG)
![1986utan](https://cloud.githubusercontent.com/assets/9251555/6634636/7fc95f38-c95b-11e4-8257-2c0d9b0b3010.PNG)

**Comment by evajerr** [comment]
Får olika reultat om jag söker på 

- sfs 1998:150 (med blanktecken efter sfs)
Denna ger en större träffmängd 
![ri 151 1](https://cloud.githubusercontent.com/assets/9693918/6638462/8b839c46-c986-11e4-90c0-07e889123464.PNG)
![ri 151 2](https://cloud.githubusercontent.com/assets/9693918/6638461/8b7e9dc2-c986-11e4-9c7e-a9ee601156b1.PNG)



- sfs1998:150  (utan blanktecken efter sfs)
Denna ger en mer exakt träff den konsoliderade författningan först och sedan grundförfattningen

**Comment by evajerr** [comment]
Varningsmeddelandet kvarstår om jag skriver en söksträng med ", fram tills det avslutanda " skrivs in i sökfälötet.
![ri 151 3](https://cloud.githubusercontent.com/assets/9693918/6638531/604be726-c987-11e4-974f-0f78b5873159.PNG)

**Comment by cheijken** [comment]
Finns med på feature/152_new_elasticbuilder

**Comment by cheijken** [comment]
Stänger.
Denna issue har arbetats på av både mig och @jeldeklint och hanteras även i ett flertal andra ärenden.
Anser att denna är väl testad och klar.

**Comment by lalindqv** [comment]
Fungerar fint, föruto om jag söker på (), se lagrummet #426

**Comment by evajerr** [comment]
NOK. Nu raknas 1979.13 ännu längre ner, 50:e plats dvs ännu lägre än innan
![ri exakttraff for langt ner](https://cloud.githubusercontent.com/assets/9693918/6802067/8985a88a-d22d-11e4-85c5-ae3ee70ba823.PNG)
.

**Comment by kamidev** [comment]
Problemet @evajerr tar upp här på slutet har inget med tvättning av indata till ElasticSearch att göra. Hänvisar istället till #163, som handlar om identifierare för rättsfall. Stänger detta ärende.
