### ISSUE TITLE
Skriv om koden som genererar Elasticsearch-frågor

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#152]
Frågorna som används idag är gamla och inte helt anpassade till vilken version av elasticsearch som körs. 
För att kunna åtgärda flera issues så som rinfo/lagrummet.se#191 rinfo/lagrummet.se#176 m.m _bör_ vi skriva om frågorna. "Boostning" av fält (#132 ) går att göra snyggare med andra frågor dessutom.

**Comment by karejonssondov** [comment]
http://wiki.lagrummet.se/index.php/Programmering_fr%C3%A5ge-API

**Comment by jeldeklint** [comment]
Finns även en commit c8923aa som uppdaterar `elasticsearch` till `1.4.2` (upptäckte att jag missade tagga comitten försent..)

För att migrera:
- skapa ett snapshot av indexet rinfo, t.ex. via http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-snapshots.html
- ladda ner och installera `1.4.2`
- stäng ner `1.2.1` och starta `1.4.2`
- återställ snapshot:et i `1.4.2`

**Comment by cheijken** [comment]
Stänger.
Omskrivningen genomförd. Omfattande testad i andra issues.
