### ISSUE TITLE
Sökningen ska respektera dokuments identifierare när söksträngen delas upp internt

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#153]
_From @lalindqv on November 17, 2014 10:13_

Om tecknet ":" (kolon) används i en söksträng feltolkas det och gör att säkning sker på tecken före __och__efter ":" 
Exempel: Sökning på 1998:144 ger träff på dokument som innehåller både 1998 och 144.

Förväntat att sökningen sker på den exakta strängen "1988:144"

_Copied from original issue: rinfo/lagrummet.se#226_

OBS! I detta ärende hanterar vi tills vidare SFS-nummer. Se även #163.

**Comment by kamidev** [comment]
_From @jeldeklint on November 17, 2014 10:30_

japp, det finns endel andra problem med söken också, vore bra att ha kraven tydliga för den någonstans när vi tar ett övergripande tag i söken..

**Comment by kamidev** [comment]
_From @lalindqv on November 18, 2014 12:53_

Håller med. Då är det nog en del att göra med kravmassan. 
Nu är den relativt strukturerad, kraven är taggade. 
Men vi skulle behöva omformulera flera av kraven. Jag vill nog helst inte utföra det arbetet i Excel, där det lätt grötar ihop sig.

**Comment by kamidev** [comment]
_From @jeldeklint on January 26, 2015 15:57_

bör hanteras i frågorna till elasticsearch, kolla på typ `analyzers / tokenizers`

**Comment by jeldeklint** [comment]
relaterar till #162 
jag har även ändrat inställningarna för `identifierare` (beteckning) och `målnummer`så att `identifierare` tokeniseras enl. `((?:\w{2,3})\s+\d{1,4}(?:\:\d{1,}|\s(?:s\.|ref\.|nr)\s+\d{1,}))` Behöver öka accepterad inledande bokstavs-kod till 4 teckens maxlängd.

**Comment by jeldeklint** [comment]
Har löst det även för `title` - trots att den svenska analyseraren används. Detta genom att använda ett `char_filter` som kör innan strängen tokeniseras och där byta `1999:175` till `1999colon175` och sedan när allt är klart använda ett annat filter för att byta tillbaka.

Kanske även borde göra det på `text`

**Comment by kamidev** [comment]
Se även https://github.com/rinfo/lagrummet.se/issues/402

**Comment by kamidev** [comment]
Se även https://github.com/rinfo/rdl/issues/166

**Comment by jeldeklint** [comment]
Den har har just nu lite problem se #179

**Comment by kamidev** [comment]
#179 är stängt.

**Comment by kamidev** [comment]
Stänger det här.  Arbetet med rättsfall går vidare i nästa release men då bör vi titta lite till på kraven, se #163.

**Comment by lalindqv** [comment]
Fungerar klart bättre än tidigare. Samma uppdelning före och efter : finns inte.
OK för nu.
