### ISSUE TITLE
Paginering gör att rättsfall "försvinner" när man söker på t.ex. SFS nummer

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#154]
_From @jeldeklint on October 14, 2014 11:53_

En bild säger mer än tusen ord?
![screenshot 2014-10-14 13 45 55](https://cloud.githubusercontent.com/assets/579622/4628536/8c37fefc-5398-11e4-8d20-575ca5797e19.png)

Det finns ju uppenbarligen träffar? är det för att de ligger så pass långt ner?

_Copied from original issue: rinfo/lagrummet.se#191_

**Comment by kamidev** [comment]
_From @jeldeklint on December 19, 2014 12:34_

funderar på om det är så att det bara visas de N bästa resultaten, oavsett kategori? Eller är det någon gränssnitsgrej? Nya JSON biblioteket?

**Comment by kamidev** [comment]
_From @jeldeklint on December 21, 2014 10:40_

Okej, har listat ut hur det kommer sig. Med till RDL vid sökning skickas en parameter för hur många resultat som skall skickas per "sida", dvs resultatet pagineras. Standard inställningen om annat inte sägs, är 50 resultat per sida.
Detta i kombination hur viktningen görs, resulterar i att Rättsfall m.m. börjar komma först på sida 2 vilken inte används vid presentation av det samlade sökresultatet.

**Comment by kamidev** [comment]
_From @jeldeklint on January 26, 2015 14:54_

Även detta borde _helst_ åtgärdas på RDL sidan i svaret från elasticsearch

**Comment by jeldeklint** [comment]
#152 kommer lösa detta, i.o.m tophits-aggregering på kategorierna.

**Comment by kamidev** [comment]
Pröva igen och se om buggen är fixad.

**Comment by lalindqv** [comment]
Verkar OK
Söker på ordet "arbetsdomstolen" som ger +6000 träffar i Rättsfall. De första 4 visas - Förväntat
Söker på ordet "avgörande" som ger +10000 träffar i Rättsfall. De första 4 visas - Förväntat

**Comment by cheijken** [comment]
Stänger.
Denna är klart och omfattande testad. Har kört en lite test nu och det ser fortfarande bra ut.

**Comment by lalindqv** [comment]
Fungerar fint.
