### ISSUE TITLE
Implementera beteende motsvarande jokertecken * sist i varje söksträng

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#155]
_From @jeldeklint on July 11, 2014 12:33_

Vi borde lägga till ett "osynligt" wildcard eller liknande i sökningen från lagrummet.
Då skulle sökresultatet för `rättsinfo` automatiskt gå från
![image](https://cloud.githubusercontent.com/assets/579622/3552478/022342fc-08f8-11e4-961b-c72edf3145ac.png)

till
![image](https://cloud.githubusercontent.com/assets/579622/3552473/eb100d52-08f7-11e4-98bd-dac2ccea5f45.png)

_Copied from original issue: rinfo/lagrummet.se#176_

**Comment by kamidev** [comment]
_From @jeldeklint on August 13, 2014 13:31_

Vi skulle även kunna ta hänsyn till hur populär en författning osv. är i sökresultatet, dvs författningar som läses ofta kommer högre upp

**Comment by kamidev** [comment]
_From @jeldeklint on January 26, 2015 10:2_

Bra läsning här är; http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/partial-matching.html speciellt om "ngrams"
Vi bör inte använda ett "vanligt" wildcard m.a.o..

**Comment by kamidev** [comment]
_From @jeldeklint on January 26, 2015 13:37_

Således bör den här förpassas till RDL och ett större omtag av elasticsearch frågorna där

**Comment by karejonssondov** [comment]
Om man skriver fel i SMS-fältet föreslår den "Möte" om man skriver "Mlte" men inte om man skriver "Mdte". På tangentbordet ligger l nära ö men d gör det inte. Är detta inom elastics räckvidd?

**Comment by kamidev** [comment]
Pröva att söka på "rättsinfo". Matchar det "Rättsinfoförordningen"?

**Comment by lalindqv** [comment]
"Räksm" fungerar utmärkt. Ger 1 förväntad träff.
"Rättsinfo" ger match på rättsinformationsförordningen.´

Däremot ger sökning på "hundsk" ett litet oväntat resultat. Jag klassar det inte som ett fel, men någonting vi bör vara medvetna om:
Jag förväntade mig att träff på "hundskallet" presenterades före "hundskräck" i Rättsfallen.
Jag förväntade mig att träff på "hundskatt" presenterade före "hundskola"

![hund](https://cloud.githubusercontent.com/assets/9251555/6618152/afe17ef8-c8c0-11e4-8afe-dd57ae93066e.PNG)

**Comment by evajerr** [comment]
Testat "flygh" och resultatet ser korrekt ut. Får träff på ett antal ord som börjar på flygh.
Test på "kamer" är inte helt klockren. Får även träff på ord som börjar på kammarrätt och det är ganska långt ifrån.
![ri github 155](https://cloud.githubusercontent.com/assets/9693918/6620059/db9c7328-c8ce-11e4-8864-5f9e9965eb75.PNG)
![ri github 155 2](https://cloud.githubusercontent.com/assets/9693918/6620077/eefdc2d2-c8ce-11e4-8e5a-44432c7a8296.PNG)

**Comment by lalindqv** [comment]
Jag tycker beteendet är helt ok eftersom antalet träffar går ner väldigt fint när man preciserar sökordet:
kam ger 1913 träffar
kamer ger 1913 träffar
kamera ger 140 träffar
kameraöver ger 89 träffar

Att man får träff på kammarrätt när man söker på "kamer" visar , tycker jag, hur elegant sökmotor vi har.

**Comment by jeldeklint** [comment]
Detta är implementerat med [`phrase_prefix`](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#_match_phrase_prefix) i elasticsearch

**Comment by lalindqv** [comment]
Ersätter krav 124 på att jokertecknet * efter sökord ska kunna hanteras.

**Comment by kamidev** [comment]
VerifieVerifierat på test.lagrummet.se och demo.lagrummet.se.

**Comment by lalindqv** [comment]
OK
sökning på "kam,...,kameraöver"  ger samma resultat som tidigare
sökning på "flygh" ger samma resultat som tidigare.
sökning på "räksm" ger samma resultat som tidigare
sökning på "hunska" ger samma resultat som tidigare
