### ISSUE TITLE
Ställ in förväntat beteende vid sökning på ordstammar respektiva ofullständiga ord

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#156]
_From @lalindqv on November 14, 2014 11:9_

Sökning på "räksmörgås" ger ingen (0) träff.
Sökning på "räksmörgåsar" ger en (1) relevant träff.

Jag hade förväntat mig att "räksmörgås" skulle ge lika många eller fler träffar än "räksmörgåsar".

Testmiljö: http://test.lagrummet.se
_Copied from original issue: rinfo/lagrummet.se#222_

Ett annat exempel är beteende vid sökning på "hund" eller "hundralapp". Vilket är det önskade beteendet? @helelun, finns det några tacksamma exempel?

**Comment by kamidev** [comment]
_From @jeldeklint on November 14, 2014 11:47_

Det här har egentligen med RDL att göra om det inte söks på lokalt material. hur som helst, se också #176 Vi borde nog skruva lite mer på elasticsearchen

**Comment by kamidev** [comment]
#176 är just nu planerad till beta6. Jag tror som @jeldeklint att vi bör ta hänsyn till alla komponenter i sökningen innan vi ger oss på den här.

**Comment by kamidev** [comment]
Flyttar den här till RDL

**Comment by kamidev** [comment]
Se även #155.

**Comment by helelun** [comment]
Ett ursprungligt krav är att sökord ska ge träff på böjningar av ett ord.
Alltså bör sökning på "räksmörgås" ge träff på det rättsfall som innehåller ordet "räksmörgåsar".
Likaså bör sökning på "hund" även ge träff på "hundar", "hunden" etc.

Noterar i exemplet räksmörgås att ordet hos källan återfinns i referatstexten men inte i rubriken.

**Comment by helelun** [comment]
När det gäller ordstammar är ett ursprungligt krav att sökord med * ger träff på del, början eller slutet av ordet (beroende på placering av *).
Exempel:
"hund*" ger träff på "hundralapp", "hundskatt", "hund".
"*skuld" ger träff på "ränteskuld", "kreditskuld", "skuld".

**Comment by jeldeklint** [comment]
jag ställer in fälten `titel`, `referatrubrik` och `text` på att analyseras med den ["svenska" analyseraren](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#swedish-analyzer) som  använder en svensk ["stemmer"](http://snowball.tartarus.org/algorithms/swedish/stemmer.html)

**Comment by jeldeklint** [comment]
Orsaken till att sånt här inte har fungerat tidigare är att alla fält har analyserats med `standard` analyseraren, vilken inte bryr sig om stemming utan bara splittar och och kollar på _engelska_ "stopwords" (dvs filtrerar bort ord som `and`, `or`, `it`)

**Comment by kamidev** [comment]
@lalindqv: pröva att söka ordstammar. Hund och katt. Hundar, hundarna et cetera.

**Comment by jeldeklint** [comment]
bra test är också sökning på `rättsinformationsförordningen` ska ge träff på `rättsinformationsförordning` också.

**Comment by evajerr** [comment]
Testat på 
- flyghönorna
- flyghönor
- flyghöns
Får samma träff (flyghöna) i alla lägen. Det känns rätt och OK
Testat på 
- dold övervakning
- dolda övervakningar
- dolda övervakningarna
Får samma träff (dold övervakning) i alla lägen. Det känns rätt och OK.

**Comment by lalindqv** [comment]
Testat handskarna, ger träff på handskar,... ( handskrift,..) 
Älgen: ger träff på älg, älgen, älgjakt, ....
Älgarna: älgarna, älg , älgjakt, älgjägare, ...

Känns OK

**Comment by helelun** [comment]
Sökning på rättsinformationsförordningen ger förväntad träff på konsoliderad version av rättsinformationsförordning. Sökning på brottsbalken ger likaså förväntad träff på konsoliderad version av brottsbalk.

Verkar ok i den delen.

**Comment by helelun** [comment]
I en kommentar i denna issue har jag noterat ett tidigare krav att man vid sökning på ett ord även skulle få träff på tidigare ordled. Exemplet är: "*skuld" ger träff på "ränteskuld", "kreditskuld", "skuld".

Detta tidigare krav ska återföras till kravdokument för senare diskussion (@lalindqv).  
Detta tidigare krav ingår inte längre i denna issue.

**Comment by jeldeklint** [comment]
Svenskt språk analyseras i fälten `text`, `title` och `referatrubrik` se `_mappings`

**Comment by cheijken** [comment]
Stänger.
Tester utförda av testare tycks fullgod. Har verifierat att den testade funktionaliteten införts på *develop* grenen. Kört några urvalda testord enligt ovan tester med positivt resultat.
