### ISSUE TITLE
Flera titlar för samma dokument kan visas

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#158]
_From @kamidev on June 13, 2014 11:29_

Underliggande data har verkligen har flera titlar. Det finns ingen verksamhetsmässigt säkert sätt att veta vilken vi ska välja. Finns det en tillräckligt bra kompromisslösning?

Det här slår igenom i lagrummet.se, där högerspalten på en dokumentsida kommer att lista flera titlar.

_Copied from original issue: rinfo/lagrummet.se#157_

**Comment by kamidev** [comment]
_From @jeldeklint on October 21, 2014 9:44_

Exempel på utseende i beta.lagrummet.se
![screenshot 2014-10-21 11 42 26](https://cloud.githubusercontent.com/assets/579622/4716288/c64257d2-5906-11e4-9290-fd4793bcb36f.png)

Har kokat ihop en experimentell, men fungerande lösning som arbetar i rinfo-service, vilket ger genomslag i lagrummet också. Se rinfo/rdl#93 och rinfo/rdl#146

**Comment by kamidev** [comment]
Denna issue är beroende av färsk data från RK.

**Comment by kamidev** [comment]
Flyttar till RDL

**Comment by jeldeklint** [comment]
det här gäller presentation i lagrummet. finns redan ett bredare ärende i rdl #146 jag tycker inte den här borde flyttats till rdl.

**Comment by kamidev** [comment]
@jeldeklint: håller med.

**Comment by lalindqv** [comment]
Kan inte testa detta.
Är det rätt eller fel att ha flera "titlar" i en författning ?
Hur lösa problemet ?
 ( Finns egenskapen "titel" i dokumentmodellen eller är det vad som benämns "rdfs:label" ? )

**Comment by lalindqv** [comment]
Se rinfo/lagrummet #157

**Comment by helelun** [comment]
Instämmer med Lars. 
Se rinfo/lagrummet #157
