### ISSUE TITLE
Skicka mail vid insamlingsfel

### ISSUE THREAD

**Issue by cheijken** [rinfo/rdl#16]
Vid fel vid på Collector, vid insamling, så behöver det skickas felmeddelanden till ansvarig tekniker hos domstolsverket, samt ansvarig tekniker på den myndighetskällan som felet härrör ifrån.

**Comment by cheijken** [comment]
Att skicka mail till ansvarig tekniker på DV är inget problem. Kan göras som en inställning i en properties fil, men att skicka mail till ansvarig tekniker för instamlingskällan, kräver ett register och mycket mera tankar. Fyller vi i informationen i myndighetsinformationen? Skall den ingå i insamlade informationen? Separat register, som kanske myndigheterna själva ansvarar för?
Möjligen behöver denna ISSUE delas upp i 2 delar. En för DV tekniker och en för insamligskällans tekniker?

**Comment by kamidev** [comment]
Dublett av #137. Stänger denna.
