### ISSUE TITLE
Ställ in miljöer för "beta"-release

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#160]
Placeholder för att inte glömma.
Är det någon som inte minns vad det här handlar om, kontakta mig.
Det den här stoyn handlar om, är blockerande för en "publik" release.

**Comment by kamidev** [comment]
Komplettera gärna intern wikisida med mer information.

**Comment by karejonssondov** [comment]
Skrev något kompletterande här: 
http://wiki.lagrummet.se/index.php/Nödvändiga_åtgärder_i_infrastrukturen

**Comment by jeldeklint** [comment]
Bra!

**Comment by karejonssondov** [comment]
Lade till adressbiten i connectorn i server.xml för Tomcat
<Connector address="127.0.0.1"
Incheckningen lyder commit c44d3f832a8f0729a47b31d9eae8584280831e34

**Comment by kamidev** [comment]
Säkerställ att dessa inställningar testas på staging-server och används vid nästa skarpa release. Se https://github.com/rinfo/lagrummet.se/issues/375

**Comment by karejonssondov** [comment]
Gjorde en hel ominstallation på systemet stage. Konstaterar att både tomcats server.xml och Virtual-host-filerna service och rinfo-main har de ändringar som står på wiki-sidan.

**Comment by kamidev** [comment]
Dags att testa att installera senaste version av release/2.2 på stage igen. Snapshot-funktionaliteten för att ladda data är testad och bör fungera bättre nu.
