### ISSUE TITLE
Uppgradera elasticsearch

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#161]
Blockerar #152 #154 
elasticsearch behöver uppgraderas till `1.4.2`
se instruktioner i #152

**Comment by karejonssondov** [comment]
Det är bara att byta från 1.2.1 till 1.4.4. Följande är den verifiering jag gjort. 

- Fyllt med 1.2.1. Kopierat över till 1.4.4. Verifierat att det fungerar med samma antal träffar på ödla och vatten. 

- Installerat 1.4.4 och tömt den och därpå kört insamlandet rinfo -> service. Verifierat med orden ödla och vatten.

Jag skriver om i fab-skripten så att 1.4.4 installeras.

**Comment by karejonssondov** [comment]
Det var inte i fab-skriptet det skulle ändras utan packages/java/pom.xml.

Genom att ändra versionssiffran på ci-maskinen samt rensa bort allt /opt/elasticsear* på stage samt initieera ominstallationen har jag verifierat att version 1.4.4 blir installerad samt börjar insamlingen från main på samma sätt som vid experimenten ovan. Jag anser detta verifierat och incheckbart.

**Comment by jeldeklint** [comment]
Kanon!

**Comment by kamidev** [comment]
Automatiska byggen och tester har fungerat några dagar. Stänger den här.
