### ISSUE TITLE
Uppdatera elasticsearch mappings med målnummer och referatrubrik

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#162]
Dessa fält har inte varit konfigurerade utan har bara lagts till dynamiskt.
refererar till #156

**Comment by kamidev** [comment]
Pröva att söka på ett målnummer. Får man träff? Vad markeras i resultatet? Jämför även issue https://github.com/rinfo/lagrummet.se/issues/402

**Comment by evajerr** [comment]
- Sökte på målnummer och fick
![ri github 162 1](https://cloud.githubusercontent.com/assets/9693918/6634841/aab993f4-c95e-11e4-810b-819a4bb9ca7a.PNG)
![ri github 162 2](https://cloud.githubusercontent.com/assets/9693918/6634842/b18f0452-c95e-11e4-9100-b3c4d4a20d22.PNG)

 förväntad träff
- Sökte på referatrubrik och hittade inte själva referatet vilket jag borde ha gjort. Hittade endast två andra referat varav det ena hade en referens till sökt referat och den andra ingenting (synligt).

**Comment by evajerr** [comment]
Söker på målnummer som finns i ett referat med två målnummer och får endast träff på det ena målnumret. Jag borde hitta referatet via båda.
![ri github 162 3](https://cloud.githubusercontent.com/assets/9693918/6634964/6b80b38c-c960-11e4-8b1f-7473b43174b8.PNG)
![ri github 162 4](https://cloud.githubusercontent.com/assets/9693918/6634965/6b87145c-c960-11e4-9b25-d80eaf91e3fb.PNG)
![ri github 162 5](https://cloud.githubusercontent.com/assets/9693918/6634963/6b804398-c960-11e4-8557-16e5406d8245.PNG)

**Comment by evajerr** [comment]
Söker på målnummer med samma avgörandedatum och förväntar mej att både eller ingen finns i RI.
Hittar bara den ena den som har ett referat. Målnummer som saknar referat hittas inte.

![ri github 168](https://cloud.githubusercontent.com/assets/9693918/6636025/78227150-c96c-11e4-88bf-e2856d61cc69.PNG)

**Comment by jeldeklint** [comment]
Målnumren som visas _ovanför_ strecket på ett _referat_ är inte sökbara idag. De skulle kunna göras sökbara genom att uppdatera https://github.com/rinfo/rdl/blob/master/packages/java/rinfo-service/src/main/resources/sparql/construct_summary.rq

**Comment by jeldeklint** [comment]
För att se att mappings finns kolla `http://localhost:9200/rinfo/_mappings` på en uppdaterad server

**Comment by cheijken** [comment]
Stänger.
Sökning ger förväntat söksvar enligt ovan exempel.
