### ISSUE TITLE
Sökning på sträng som inte hittas ger stort antal träffar

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#165]
Inrapporterat på Viktor under pågående utveckling.  Se bifogad skärmbild. Samma fel slår igenom även på lagrummet.

**Comment by kamidev** [comment]
![skarmavbild 2015-03-06 kl 16 25 25](https://cloud.githubusercontent.com/assets/1655/6527735/73c3b99c-c41d-11e4-9162-ee34e78a7aec.png)

**Comment by lalindqv** [comment]
Rappakalja ger också 9440 träffar:

![sok pa vad som helst](https://cloud.githubusercontent.com/assets/9251555/6551668/7f36ef08-c63c-11e4-91b5-5225493670d3.PNG)

**Comment by cheijken** [comment]
Detta beror på att vi "boostat" upp vissa type av träffar som konsoliderade dokument, men inte lagt på en minsta nivå, så att för mycket kommer med.

**Comment by kamidev** [comment]
Pröva igen och se om antalet träffar är korrekt nu.

**Comment by lalindqv** [comment]
Ser ok ut. Sökning på t.ex. slumpsträngar ger tex 0 träffar, vilket är förväntat.

**Comment by evajerr** [comment]
OK
Sökte på nonsens och fick noll träffar
![ri github 165](https://cloud.githubusercontent.com/assets/9693918/6621206/983322c4-c8d5-11e4-826d-7ccf22ceb819.PNG)

**Comment by cheijken** [comment]
Samma som #168. Finns med i **feature/152_new_elasticbuilder**

**Comment by cheijken** [comment]
Stänger. Visserligen står på mig. Men egentligen @jeldeklint som löst den.
Testat och kontrollerat antalen i träffar. De är som förväntat.

**Comment by lalindqv** [comment]
OK - sökning på rappakalja ger nu 0 träffar, vilket är förväntat.
