### ISSUE TITLE
Sökning på identifierare borde ge mer exakt träff

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#166]
_From @kamidev on March 6, 2015 14:21_

_Copied from original issue: rinfo/lagrummet.se#401_

**Comment by kamidev** [comment]
_From @lalindqv on March 9, 2015 7:34_

Eva:
Jag hittar vad jag söker men även en massa onödiga träffar och jättemånga sådana eftersom sökningen plockar upp ”sfs” som ett sökbegepp.
                                            Sfs 1998:150 är en beteckning och jag undrar om inte systemet ska känna igen /förstå det?  
![401](https://cloud.githubusercontent.com/assets/9251555/6551328/0653c016-c637-11e4-8e3d-77207cd41d93.PNG)

**Comment by evajerr** [comment]
- Frågade på SFS 1998:150
Nu ligger svaret mycket närmare sökordet. Jag tycker att det är OK.
- Frågade även på 1998:150
Fick en större träffmängd (hade ev förväntat mej en mindre när SFS inte var med) men fick 
![ri github 166 1](https://cloud.githubusercontent.com/assets/9693918/6620862/7246a6b4-c8d3-11e4-882c-3f3bf6730512.PNG)
![ri github 166 2](https://cloud.githubusercontent.com/assets/9693918/6620874/7fdf1e1e-c8d3-11e4-840e-2682a95c8c15.PNG)

ett JÄTTESVAR från AD men det kanske är en annan fråga. Ser ut som ett vulkanutbrott eller en tsunami.

**Comment by cheijken** [comment]
Vad är det som skall lösas i denna issue.
Jag utläser en ny/nytt aktivitet/problem vid varje nytt inlägg.
Dessutom så tycks inga av dessa ärenden vara aktuella längre. Samtliga lösta.
Stänga? @kamidev @helelun

**Comment by kamidev** [comment]
Verifierat på test.lagrummet.se och demo.lagrummet.se

**Comment by evajerr** [comment]
OK. Hittar sfs 1998:150 både med och utan sfs i sökbegreppet.
