### ISSUE TITLE
Duplikat visas i träfflista

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#167]
_From @kamidev on March 6, 2015 15:32_

_Copied from original issue: rinfo/lagrummet.se#405_

**Comment by kamidev** [comment]
_From @lalindqv on March 9, 2015 9:23_

Sökord:                              mig 2014:20
Kommentar:                      Träfflistan visar 3 resultat
                                            Rättsfall (2) indikerar att det eg är två träffar.
                                            Träff 1 och 2 är vad jag kan se ”indentiska”. 

![405](https://cloud.githubusercontent.com/assets/9251555/6552455/4640c5a2-c646-11e4-95be-2ea5061f62cb.PNG)

**Comment by lalindqv** [comment]
Ytterligare ett exempel från Eva:
Åtminstone dokument 911-15, RÅ 2004 ref 44 och HFD 2012 ref 16  förekommer två gånger i resultatet.

![duplikat](https://cloud.githubusercontent.com/assets/9251555/6553389/7bf6c610-c650-11e4-8d41-3c061b9fc8c4.PNG)

**Comment by cheijken** [comment]
Stänger.
Felet låg i lagrummet.

**Comment by lalindqv** [comment]
Duplikat av lagrummet #405
