### ISSUE TITLE
Irrelevanta träffar i Lagar och förordningar. Träff på sökord saknas

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#168]
_From @kamidev on March 6, 2015 14:19_

Får inga gulmarkeringar och antagligen inga träffar
                                            Antal träffar = 9440 men det är mer troligt att 0 träffar stämmer

![fotoforbud](https://cloud.githubusercontent.com/assets/9251555/6551234/58fb2c16-c635-11e4-970e-ae0f2f8ce52e.PNG)

eller ännu tydligare , om man söker på något som inte borde finnas:
![sok pa vad som helst](https://cloud.githubusercontent.com/assets/9251555/6551245/73380220-c635-11e4-9bac-4f85be39eda0.PNG)

_Copied from original issue: rinfo/lagrummet.se#400_

**Comment by cheijken** [comment]
Denna hänger ihop med samma grundfel som #165 och har bland annat att göra med att vi boostar konsoliderade grundförfattningar, men sedan inte filtrerar bort dem. Man får alltså träff på konsoliderade grundförfattningar trots att det inte finns i sökordet.

**Comment by kamidev** [comment]
Pröva om vi har träffar nu. 

Sök på något annat än målnummer. För närvarande kommer inte målnummer att gulmarkeras korrekt.

**Comment by evajerr** [comment]
![ri github 168](https://cloud.githubusercontent.com/assets/9693918/6620426/edb45b46-c8d0-11e4-931c-cbeaa4ece918.PNG)
OK 
Sökte på div ord som inte ger någon träff. 
- fotoförbud - ger noll träffar
- fotofötbud råder - ger noll sträffar

**Comment by cheijken** [comment]
Har tagit bort generell boostning av alla konsolideringar. **feature/152_new_elasticbuilder**

**Comment by cheijken** [comment]
Stänger.
Huvudsakligen löst i lagrummet. Men viss boostning i elastic search har också påverkat negativt.
Testat och det ser bra ut.

**Comment by evajerr** [comment]
OK. Ser inga konstigheter. Har testat på div ord och ordkombinationer.
