### ISSUE TITLE
Ersätt "org.codehaus" med annan källa i pom.xml

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#169]
Codehaus.org kommer att upphöra som publik repository april 2015. Vi bör leta upp alla nödvändiga byggberoenden i pom.xml och ersätta med fungerande alternativ.

**Comment by cheijken** [comment]
Missade att tagga commit  71cdaf5 som har med denna att göra.

**Comment by cheijken** [comment]
Fixat i RDL och lagrummet commit https://github.com/rinfo/lagrummet.se/commit/3e86c4430347428b0419af963339be8ac8a90e7b
Borde bygga utan fel nu.

**Comment by kamidev** [comment]
Bygger utan fel. Veriferat på demo.lagrummet.se.
