### ISSUE TITLE
Förbättra stöd för synonymer som parametrar vid sökning

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#170]
Vid sökning på flera termer (d v s en huvudterm och flera synonymer) ska synonymerna hanteras speciellt av ElasticSearch.

**Comment by jeldeklint** [comment]
synonymen `PUL` ska exempelvis _givetvis_ ge resultat för `Personuppgiftslag (1998:204)`

**Comment by jeldeklint** [comment]
synonymerna slutade fungera när jag slog på escaping av synonymer också

**Comment by cheijken** [comment]
Stänger.
Har testat med synonym *skilsmässa* till *äktenskapsskillnad* och det fungerar bra.
Notera att det finns en bugg #179 som gör att synonymer med vissa tecken inte fungerar.
Notera även att det kan finnas kvar lite arbete med viktningen av synonymer.
