### ISSUE TITLE
Se till att sökgränssnittet på service.lagrummet.se fungerar mot ny sökfunktionalitet

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#171]

**Comment by jeldeklint** [comment]
ska vara fixat i.o.m f90edad1d och db93eaf648

**Comment by cheijken** [comment]
Stänger.
Har testat service med sökord och navigering. Fungerar ok. 
Notera att tom söksträng inte fungerar, men jag tycker det är good enough som det är.
