### ISSUE TITLE
Referat ska sorteras högre än mål

### ISSUE THREAD

**Issue by kamidev** [rinfo/rdl#174]
_From @kamidev on March 6, 2015 15:33_

_Copied from original issue: rinfo/lagrummet.se#406_

**Comment by kamidev** [comment]
_From @lalindqv on March 9, 2015 9:35_

Eva: 
Sökord: förhandsavgörande arbetsdomstolen
Först presenteras/listas alla målnummer (och man kommer till den tråkiga sidan som bara fyller en funktion när referat saknas?)

Därefter, en bra bit ner, presenteras dito referat (den intressanta informationen).  Jag antar att man är mest intresserad av referaten och de borde i så fall komma först i listningen.

Detta är alltså fel:
![406](https://cloud.githubusercontent.com/assets/9251555/6552602/bdc5d1b6-c647-11e4-86aa-a87d9d34fffd.PNG)

**Comment by kamidev** [comment]
_From @jeldeklint on March 10, 2015 12:39_

den här hör också hemma i `rinfo/rdl`

**Comment by kamidev** [comment]
Sök på text som förekommer i mål/avgöranden och se hur resultet blir. Hur sorteras sökresultatet? 

Ta gärna fram flera bra exempel på önskat utfall! @helelun, @jeldeklint?

**Comment by jeldeklint** [comment]
någon sortering sker inte alls, därimot sker lite viktning mot `Rattsfallsreferat`

**Comment by jeldeklint** [comment]
Viktningen idag är mot `Rattsfallsreferat`, jag är osäker på om det är rätt dokumenttyp

**Comment by evajerr** [comment]
Testade samma sökord igen (förhandsavgörande arbetsdomstolen) och sorteringen/prioriteringen
 verkar mycket bättre. På första sidan kommer referat från AD. Sedan är det lite blandat referat och målnummer. Om det är tillräckligt bra kan jag inte avgöra men jag kan bara säga att första sidan är mer relevant nu.

**Comment by jeldeklint** [comment]
genom 2a9728e204 görs referaten dubbelt värda

**Comment by cheijken** [comment]
Stänger.
Verifierat inne i develop. Testat samma resultat som eva.

**Comment by evajerr** [comment]
OK. Samma som Lagr 406.
