### ISSUE TITLE
Rinfo Service laddar inte

### ISSUE THREAD

**Issue by lalindqv** [rinfo/rdl#178]
Gåller åtminstone Ville, Valle och Viktor. Ser ut så här efter en minuts väntan:
![valle1](https://cloud.githubusercontent.com/assets/9251555/6684730/45556360-cc94-11e4-852e-e0fa2b1ed2a2.PNG)

Medan Betan laddar inom ett par sekunder: 
![beta1](https://cloud.githubusercontent.com/assets/9251555/6684739/53b94052-cc94-11e4-9105-06952444c400.PNG)

**Comment by jeldeklint** [comment]
kopia av #171 det är fixat men inte deployat till testmiljöer.

**Comment by lalindqv** [comment]
Fungerar ej på Ville (laddar ej)
Funkar på Valle
Fungerar ej på Viktor (laddar ej)

**Comment by jeldeklint** [comment]
Testa igen, fungerar nu - du måste ha provat precis när jag sparkade på dem. De var i läget "borde inte fungera men fungerar" typ allmänt kaos med halv-installerad rdl som gick mot fel es-index osv.

**Comment by lalindqv** [comment]
Alla tre VVV laddar snabbt.
