### ISSUE TITLE
Ändra vilka specialtecken som escapas till elastic (och kanske var)

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#179]
releaterar till #151 
vissa tecken t.ex. `:`,`(` och `)` bör inte escape:as i indatat till elastic då sökningen inte klarar av att analysera alla `\\` inne i t.ex. identifierare.
dock måste t.ex. `"` även i fortsättningen vara escapad (annars exploderar saker)

**Comment by cheijken** [comment]
Stänger.
Test av sök på PUL. Ger korrekt resultat.

**Comment by lalindqv** [comment]
Fungerar bra, förutom om jag söker på ().  Se separat rapport rinfo/lagrummet #426
