### ISSUE TITLE
Div. fixar för elasticsearch analyzerare

### ISSUE THREAD

**Issue by jeldeklint** [rinfo/rdl#180]
se rinfo/lagrummet.se#416 rinfo/lagrummet.se#415 rinfo/lagrummet.se#414

**Comment by jeldeklint** [comment]
Fungerar rätt bra nu! Den klarar nu att hålla koll på målnummer, både med och utan inledande bokstav

**Comment by cheijken** [comment]
Stänger.
Har testat på test.lagrummet.se. Det fungerar ok. 
För att detta skall få genomslag, behövs uppdatering ske i elasticsearch, genom omindexeras enligt http://wiki.lagrummet.se/index.php/Elasticsearch,_indexera_om_/_flytta_till_nytt_index.
Kvarvarande rinfo/lagrummet.se#414 behöver en ny issue. @kamidev
