### ISSUE TITLE
Hittar inte referat som är exakt angivet 

### ISSUE THREAD

**Issue by evajerr** [rinfo/rdl#188]
Söker på referat som jag vet finns nja 2005 s.263. Detta referat hör ihop med målnummer B4647-04 på HD. 
Hittar bara referatet om jag frågar på målnummer men borde hitta det när jag anger referatnummer.

![ri referat](https://cloud.githubusercontent.com/assets/9693918/6806067/da891438-d246-11e4-9e8d-7e087e69b255.PNG)

![ri malnummer](https://cloud.githubusercontent.com/assets/9693918/6806168/5fa8a1ba-d247-11e4-864f-18135ccdd045.PNG)

**Comment by jeldeklint** [comment]
samma grej som i rinfo/lagrummet.se#412
det är för att det ska sitta ett blanksteg mellan `s.` och `263`. Rättstavning på sånt är på G i rinfo/lagrummet.se#414

**Comment by helelun** [comment]
Felrapport beror på felaktig inmatning. Stängs utan åtgärd. Se ärenden i lagrummet.se.
