### ISSUE TITLE
Kolumn referat/dom visar målnummer istf referat

### ISSUE THREAD

**Issue by evajerr** [rinfo/rdl#192]
Kolumnen Referat/Dom innehåller målnummer istf referat. Det stämmer inte med VA's nomenklatur.

![ri referatdom](https://cloud.githubusercontent.com/assets/9693918/6821666/4d189a2c-d2d9-11e4-8bd1-553aacdc84b6.PNG)
![ri referatdom2](https://cloud.githubusercontent.com/assets/9693918/6821667/4d18cb82-d2d9-11e4-8d34-c09a254d2e0e.PNG)

**Comment by jeldeklint** [comment]
Osäker, refererar man inte till en dom med målnummer? För en dom är väl domstolens avgörande i ett mål? Och ett referat kan beskriva avgöranden i flera mål?

**Comment by kamidev** [comment]
Flyttar det här till lagrummet.

**Comment by kamidev** [comment]
This issue was moved to rinfo/lagrummet.se#430

**Comment by kamidev** [comment]
Kommentar från @evajerr: 

Om referat saknas i VA och dom finns så visas INTE målnummer i kolumen för Referat/Dom.
Då är den blank.
ri referatdom3
