### ISSUE TITLE
Långa svarstider vid sök på exakt SFS-nr

### ISSUE THREAD

**Issue by evajerr** [rinfo/rdl#202]
Kör på Ville.
Upplever att svarstiderna tar längre tid än vanligt.
Det tar tid innan den dynamiska sökningan svarar och när jag trycker sök så tar det också lång tid.

Frågade på en exsakt SFS. 
SFS 1985:658 

Den dynamiska gav över 700 träffar/förslag och Sök gav 2 träffar
Söksträngen för den dynamiska är godtyckligt vald ibland SFS 19 alternativt SFS 1985.

![ri svarrtidsfel](https://cloud.githubusercontent.com/assets/9693918/7456368/4ba197fa-f284-11e4-8794-a9c28775752d.PNG)

**Comment by cheijken** [comment]
Noterade att Elastic search hade problem. Flertalet fel i loggen om något som gav intrycket av att delar av elastic search arbetade mot index "rinfo_2" vilket inte existerade. Processen hade dessutom låst sig, så var tvungen att köra "kill -9". Efter omstart tycktes detta felet inte finnas kvar.

**Comment by evajerr** [comment]
Felet är åtgärdat och jag stänger felrapporten
