### ISSUE TITLE
Collectorn bör inte tillåta dokument som saknar md5-checksumma

### ISSUE THREAD

**Issue by mtiasp** [rinfo/rdl#70]
Collectorn veriferar visserligen att en eventuellt angiven md5-checksumma för ett visst dokument stämmer överens med dess faktiska md5-checksumma (genom att beräkna det och jämföra). 

Men: om ingen md5-checksumma alls är angiven så kommer collectorn acceptera dokumentet ändå. Detta bör inte vara möjligt eftersom det då inte går att verifiera att rätt dokument samlats in.

Exempel på entry/dokument där md5-checksumman saknas (för pdf-dokumentet) och alltså inte ska accepteras:

````
<entry>
<id>http://rinfo.lagrummet.se/publ/sfs/2012:34</id>
<updated>2012-02-07T11:13:21Z</updated>
<published>2012-02-07T11:13:21Z</published>
<title>2012:34 Förordning (2012:34) om utökade möjligheter till delegering i förvaltningsrätt</title>
<summary/>
<link rel="alternate" href="2012_34_grund.xhtml" type="application/rdf+xml" length="1237" le:md5="c87233cfb4701017d2547684fe556ec8"/>
<content src="http://somedomain.se/000655.pdf" type="application/pdf" />
</entry>
````

Exempel på där md5-checksumman istället finns angiven:

````
<entry>
<id>http://rinfo.lagrummet.se/publ/sfs/2012:34</id>
<updated>2012-02-07T11:13:21Z</updated>
<published>2012-02-07T11:13:21Z</published>
<title>2012:34 Förordning (2012:34) om utökade möjligheter till delegering i förvaltningsrätt</title>
<summary/>
<link rel="alternate" href="2012_34_grund.xhtml" type="application/rdf+xml" length="1237" le:md5="c87233cfb4701017d2547684fe556ec8"/>
<content src="http://somedomain.se/000655.pdf" type="application/pdf" hash="md5:f9d5a7e92c5c44911b4e447d94910dc4" />
</entry>
````

**Comment by kamidev** [comment]
Av praktiska skäl tillåter vi redan detta och hanterar det senare i processen. Stänger denna utan åtgärd.
